[package]
name = "finances"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = { version = "1.0.48", default-features = false, features = ["alloc"] }